### ISSUE TITLE
TypeError: Cannot destructure property 'pathname' of 'url' as it is undefined.

### ISSUE THREAD

**Issue by adhamfarrag** [jarda-svoboda/sveltekit-i18n#27]
Hi, after I copied and pasted code in repo description I get this error.

```js

TypeError: Cannot destructure property 'pathname' of 'url' as it is undefined.
    at __layout.svelte:77:18
    at Generator.next (<anonymous>)
    at eval (/website/src/routes/__layout.svelte:44:66)
    at new Promise (<anonymous>)
    at __awaiter /website/src/routes/__layout.svelte:21:9)
    at load (/website/src/routes/__layout.svelte:142:27)
    at load_node (/website/node_modules/@sveltejs/kit/dist/ssr.js:818:30)
    at respond_with_error (/website/node_modules/@sveltejs/kit/dist/ssr.js:904:23)
    at async respond$1 (website/node_modules/@sveltejs/kit/dist/ssr.js:1119:13)
    at async render_page (/website/node_modules/@sveltejs/kit/dist/ssr.js:1186:20)
```

Here's my Script tag

```js
	import { locale, loadTranslations } from '$lib/translations';

	export const load = async ({ url }) => {
		const { pathname } = url;

		const defaultLocale = 'en';

		const initLocale = locale.get() || defaultLocale;

		await loadTranslations(initLocale, pathname);

		return {};
	}
```

**Comment by jarda-svoboda** [comment]
I guess you are not using the latest SvelteKit, right? There is an API change in [1.0.0-next.208](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next208)…
